#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

# Argument Checking -> script take 4 arguments.
# file, IP, username, PATH_TO_SSH_KEY
if [ "$#" -eq 4 ]
then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
