#!/usr/bin/env bash
# script that install nginx into the system
sudo apt-get -y update
sudo apt-get -y install nginx
echo -e "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
