#!/usr/bin/env bash
# script that install nginx into the system
sudo apt-get -y update
sudo apt-get -y install nginx
echo -e "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sed -i "/redirect_me/ a\\\terror_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
