#!/usr/bin/env bash
# install nginx

apt-get install -y nginx

# create index.html file
mkdir -p /var/www/html
touch /var/www/html/index.html

# print hello word into index.html
echo "Hello World!" > /var/www/html/index.html

# create 404.html file
touch /var/www/html/404.html

# print "Ceci n'est pas une page" into 404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https//YouTube.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

# restart nginx
service nginx restart

