#!/usr/bin/env bash
# script that install load balancer into your system

# update pacheges
sudo apt-get update

# install and Configure haproxy
sudo apt-get install haproxy -y
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 386577-web-01 18.234.253.165:80 check
    server 386577-web-02 100.25.196.203:80 check
EOT

sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo systemctl start haproxy
sudo systemctl enable haproxy
