#!/usr/bin/env bash
# install load balancer

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get -y install haproxy

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

sudo sed -i "$ a\listen 386577-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 386577-web-02 100.25.196.203:80 check\n\tserver 386577-web-01 18.234.253.165:80 check" /etc/haproxy/haproxy.cfg

sudo service haproxy start
