#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.
# script accepts one argument that is the password used to connect to the MySQL database

cur_date=$(date +'%d-%m-%Y');
file="$cur_date.tar.gz";
mysqldump --all-databases -u -root --password="$1"> backup.sql;
tar -czvf "$file" backup.sql;
