#!/usr/bin/env bash
# Bash script that:
#	Creates the file /var/run/myscript.pid containing its PID
#	Displays To infinity and beyond indefinitely
#	Displays I hate the kill command when receiving a SIGTERM signal
#	Displays Y U no love me?! when receiving a SIGINT signal
#	Deletes the file /var/run/myscript.pid and terminates itself when
#	    receiving a SIGQUIT or SIGTERM signal

# Deletes the file /var/run/myscript.pid
terminator() {
  rm /var/run/myscript.pid
  exit
}

# Creates the file /var/run/myscript.pid containing its PID
echo "$$" > /var/run/myscript.pid

while true
do
	# Displays To infinity and beyond indefinitely
	echo "To infinity and beyond"
	# take 2 second to display
	sleep 2
	# Displays Y U no love me?! when receiving a SIGINT signal
	trap 'echo "Y U no love me?!"' SIGINT
	# Displays I hate the kill command when receiving a SIGTERM signal
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	# call terminator
	trap 'terminator' SIGQUIT
done
