#!/usr/bin/env bash
# Bash script that displays Best School 10 times.

count=1
n=9
while [ $count -le 10 ]
do
    if [ $count -eq $n ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    count=$(( count + 1 ))
done
