#!/usr/bin/env bash
# script that switch user from root to the user passed as an argument
# and run the whoami command under the user passed as an argument.
user="$1"
su "$user" -s /bin/bash -c "whoami"
