#!/usr/bin/env bash
# Using what I did for task #1, make your fix short and sweet.
pkill -f apache2
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
